USE [TeamA_Project]

CREATE TABLE UsedBookOrders (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	OrderNo NCHAR(20) NOT NULL,
	OrderStatus TINYINT NOT NULL DEFAULT(0),
	PaymentStatus TINYINT NOT NULL DEFAULT(0),
	DeliveryStatus TINYINT NOT NULL DEFAULT(0),
	PaymentMethod TINYINT NOT NULL DEFAULT(0),
	DeliveryMethod TINYINT NOT NULL DEFAULT(0),
	BuyerId UNIQUEIDENTIFIER NOT NULL,
	SellerId UNIQUEIDENTIFIER NOT NULL,
	BookId UNIQUEIDENTIFIER NOT NULL,
	Title NVARCHAR(50) NOT NULL,
	SalePrice DECIMAL(10,2) NOT NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT(GETUTCDATE()),
    UpdatedAt DATETIME2 NOT NULL,

	CONSTRAINT UQ_UsedBookOrders_OrderNo UNIQUE (OrderNo),
	CONSTRAINT FK_UsedBookOrders_BuyerId FOREIGN KEY (BuyerId) REFERENCES Users(UID),
	CONSTRAINT FK_UsedBookOrders_SellerId FOREIGN KEY (SellerId) REFERENCES Users(UID),
	CONSTRAINT FK_UsedBookOrders_BookId FOREIGN KEY (BookId) REFERENCES UsedBooks(Id)
);